### ISSUE TITLE
Proposal: move teo-center-of-masses.csv to teo-developer-manual

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-simox-models#2]
[teo-center-of-masses.csv](https://github.com/roboticslab-uc3m/teo-simox-models/blob/551e1dc678eceea9a3ba416d7f584827a244df62/doc/teo-center-of-masses.csv) is really cool!

@AlvaroMartinezR Could we move it to https://github.com/roboticslab-uc3m/teo-developer-manual ?

**Comment by AlvaroMartinezR** [comment]
Done, moved [here](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/master/assets/teo-center-of-masses.csv). but now I realize that this one was quite specific to the simox environment, because in openrave defining the CoM doesnt work the same. But I am not sure because openrave is not my field.

**Comment by jgvictores** [comment]
Thanks a lot!!!

The best option would be to hyperlink from within https://github.com/roboticslab-uc3m/teo-developer-manual/blob/master/appendix/a-teo-diagrams.md, where you can explain how to interpret the values.

Don't worry about OpenRAVE specifics, this is also important for KDL and any other library/simulator. Each system will use its own conventions, so if you link or explain the interpretation, you're doing a big favor to everyone! :-)

**Comment by AlvaroMartinezR** [comment]
You can link them, but as I told you that I realized after the change, teo-center-of-masses.csv has redundant information from here https://github.com/roboticslab-uc3m/teo-developer-manual/appendix/b-teo-dynamic-information.md . Thats why I kept this file separated in the simox repository because is already prepared for it. I did it long ago so I was slow recalling it. 

My proposal is to revert it to it was or to delete it. options:

- Deleting it: well, we have it in the [appendix b](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/master/appendix/b-teo-dynamic-information.md) but for only reaching the center of masses it would be painful scrolling to the whole document.
- Reverting the change: will make it easier to extract only the CoM information.

**Comment by jgvictores** [comment]
Small note: nothing to do here. The following do not contain redundant info:
- https://github.com/roboticslab-uc3m/teo-developer-manual/blob/370c510d56ecbec83f79946320917d47acf5ddf1/appendix/b-teo-dynamic-information.md
- https://github.com/roboticslab-uc3m/teo-developer-manual/blob/370c510d56ecbec83f79946320917d47acf5ddf1/assets/teo-center-of-masses.csv

Everything is good!
